// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "hyyQwkE2jHndh45nXMsTlcbrPX1DU66VxGdTefaGttWQPjH9I5JhbwQrGHevfZ2SIRpVaz";
}
}
}

