// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "rFQxs6IxAH2hacsT30r8hlQz9WQLRe0sO97lqDqD860n3fPt14ZmP6OpINN5RLHYpVT1ka";
}
}
}

