// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "19gGTP9hJMZ6WSvF4n3uHVDVPHrMlQaZK05anQT7Nq1nHYN22CDedBUn68WEH5ZXXiJbBt";
}
}
}

